### ISSUE TITLE
Finish the implementing a 'window.hpp' and 'window.cpp' to project 🐱‍👤

### ISSUE THREAD

**Issue by NukeZzZin** [NukeZzZin/warp#5]
**_I would try to implement more functions a '[window.hpp](https://github.com/NukeZzZin/warp/blob/master/includes/window.hpp)' and '[window.cpp](https://github.com/NukeZzZin/warp/blob/master/src/window.cpp)'_** ✔

## 🐱‍👤 Features
- [x] **_auto resize to window_**
- [x] **_add a basic error handler_**
- [ ] **_buffer of the 'video' render_**  
- [ ] **_add audio to window_**
- [x] **_optimize a ram usage_**
- [x] **_optimize a cpu usage_**
- [x] **_optimize a gpu usage_**
- [x] **_add a basic handlers_**

**Comment by NukeZzZin** [comment]
> **_I would try to implement more functions a '[window.hpp](https://github.com/NukeZzZin/warp/blob/master/includes/window.hpp)' and '[window.cpp](https://github.com/NukeZzZin/warp/blob/master/src/window.cpp)'_** ✔
> 
> ## 🐱‍👤 Features
> * [x]  **_auto resize to window_**
> * [x]  **_add a basic error handler_**
> * [ ]  **_buffer of the 'video' render_**
> * [ ]  **_add audio to window_**
> * [x]  **_optimize a ram usage_**
> * [ ]  **_add environment variables to '[CMakeLists.txt](https://github.com/NukeZzZin/warp/blob/master/CMakeLists.txt)'_**
> * [ ]  **_optimize a cpu usage_**
> * [ ]  **_optimize a gpu usage_**
> * [x]  **_add a basic handlers_**

**_task: add a basic handlers - incomplete implementation_** ✔
